# Generated by Django 5.1.4 on 2025-07-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='calorieGoal',
            field=models.IntegerField(default=2000),
        ),
    ]
