# Generated by Django 5.1.4 on 2025-07-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_consume_caloriegoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='calorieGoal',
        ),
    ]
